CREATE TABLE IF NOT EXISTS `EMPLOYEE` (
  `ID` INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `EMPLOYEE_NAME` VARCHAR(255) NOT NULL,
  `EMPLOYEE_SALARY` VARCHAR(255) NOT NULL,
  `DEPARTMENT` VARCHAR(255) NOT NULL
);